# agent: { description, prefixes }
component_mapping_dynamic_form_agent = {
    "dynamic-form-general": { # Nombre de Agente
        "description": "Consultas sobre componente dynamic-form",
        "prefixes": ["dynamic-form-interface", "dynamic-form-definition", "dynamic-form-usage"] # Nombre de archivos .md a consultar
    },
    "dynamic-form-template": { # Nombre de Agente
        "description": "Consultas sobre componente dynamic-form y template",
        "prefixes": [
            "checkbox-template", "dropdown-template", "dropdown-multi-select-template", "input-number-template",
            "input-text-template", "input-text-area-template", "radio-button-template", "slider-template",
            "switch-template", "calendar-template", "password-meter-template",
            "dynamic-form-interface", "dynamic-form-definition", "dynamic-form-template-usage"
        ] # Nombre de archivos .md a consultar
    }
}

# Diccionario de componentes en inglés y español
# query: agent
component_mapping_dynamic_form_query = {
    # dynamic-form-general
    "ilibtbdynamicform": "dynamic-form-general",
    "libtbdynamicformmodule": "dynamic-form-general",
    "lib-tb-dynamic-form": "dynamic-form-general",
    "formulario": "dynamic-form-general",
    "formularios": "dynamic-form-general",
    # dynamic-form-template
    "crea template a los componentes": "dynamic-form-template",
    "crea templates a los componentes": "dynamic-form-template",
    "creale template a los componentes": "dynamic-form-template",
    "creale templates a los componentes": "dynamic-form-template",
    "crear template a los componentes": "dynamic-form-template",
    "crear templates a los componentes": "dynamic-form-template",
    "crearle template a los componentes": "dynamic-form-template",
    "crearle templates a los componentes": "dynamic-form-template",
    "crea template a cada componente": "dynamic-form-template",
    "crea templates a cada componente": "dynamic-form-template",
    "creale template a cada componente": "dynamic-form-template",
    "creale templates a cada componente": "dynamic-form-template",
    "crear template a cada componente": "dynamic-form-template",
    "crear templates a cada componente": "dynamic-form-template",
    "crearle template a cada componente": "dynamic-form-template",
    "crearle templates a cada componente": "dynamic-form-template",
    "a cada componente crea template": "dynamic-form-template",
    "a cada componente creale template": "dynamic-form-template",
    "a cada componente crear template": "dynamic-form-template",
    "a cada componente crearle template": "dynamic-form-template",
    "a cada componente crea templates": "dynamic-form-template",
    "a cada componente creale templates": "dynamic-form-template",
    "a cada componente crear templates": "dynamic-form-template",
    "a cada componente crearle templates": "dynamic-form-template",
    "a cada componente del form crea template": "dynamic-form-template",
    "a cada componente del form creale template": "dynamic-form-template",
    "a cada componente del form crear template": "dynamic-form-template",
    "a cada componente del form crearle template": "dynamic-form-template",
    "a cada componente del form crea templates": "dynamic-form-template",
    "a cada componente del form creale templates": "dynamic-form-template",
    "a cada componente del form crear templates": "dynamic-form-template",
    "a cada componente del form crearle templates": "dynamic-form-template",
    "a cada componente del dynamic form crea template": "dynamic-form-template",
    "a cada componente del dynamic form creale template": "dynamic-form-template",
    "a cada componente del dynamic form crear template": "dynamic-form-template",
    "a cada componente del dynamic form crearle template": "dynamic-form-template",
    "a cada componente del dynamic form crea templates": "dynamic-form-template",
    "a cada componente del dynamic form creale templates": "dynamic-form-template",
    "a cada componente del dynamic form crear templates": "dynamic-form-template",
    "a cada componente del dynamic form crearle templates": "dynamic-form-template",
    "a cada componente del dynamic-form crea template": "dynamic-form-template",
    "a cada componente del dynamic-form creale template": "dynamic-form-template",
    "a cada componente del dynamic-form crear template": "dynamic-form-template",
    "a cada componente del dynamic-form crearle template": "dynamic-form-template",
    "a cada componente del dynamic-form crea templates": "dynamic-form-template",
    "a cada componente del dynamic-form creale templates": "dynamic-form-template",
    "a cada componente del dynamic-form crear templates": "dynamic-form-template",
    "a cada componente del dynamic-form crearle templates": "dynamic-form-template",
    "a cada componente del formulario crea template": "dynamic-form-template",
    "a cada componente del formulario creale template": "dynamic-form-template",
    "a cada componente del formulario crear template": "dynamic-form-template",
    "a cada componente del formulario crearle template": "dynamic-form-template",
    "a cada componente del formulario crea templates": "dynamic-form-template",
    "a cada componente del formulario creale templates": "dynamic-form-template",
    "a cada componente del formulario crear templates": "dynamic-form-template",
    "a cada componente del formulario crearle templates": "dynamic-form-template",
    "a cada componente del formulario dinamico crea template": "dynamic-form-template",
    "a cada componente del formulario dinamico creale template": "dynamic-form-template",
    "a cada componente del formulario dinamico crear template": "dynamic-form-template",
    "a cada componente del formulario dinamico crearle template": "dynamic-form-template",
    "a cada componente del formulario dinamico crea templates": "dynamic-form-template",
    "a cada componente del formulario dinamico creale templates": "dynamic-form-template",
    "a cada componente del formulario dinamico crear templates": "dynamic-form-template",
    "a cada componente del formulario dinamico crearle templates": "dynamic-form-template",
    "a cada componente del formulario dinámico crea template": "dynamic-form-template",
    "a cada componente del formulario dinámico creale template": "dynamic-form-template",
    "a cada componente del formulario dinámico crear template": "dynamic-form-template",
    "a cada componente del formulario dinámico crearle template": "dynamic-form-template",
    "a cada componente del formulario dinámico crea templates": "dynamic-form-template",
    "a cada componente del formulario dinámico creale templates": "dynamic-form-template",
    "a cada componente del formulario dinámico crear templates": "dynamic-form-template",
    "a cada componente del formulario dinámico crearle templates": "dynamic-form-template",
    "formulario con template": "dynamic-form-template",
    "formulario y template": "dynamic-form-template",
    "formulario + template": "dynamic-form-template",
    "formulario más template": "dynamic-form-template",
    "formulario mas template": "dynamic-form-template",
    "formularios con template": "dynamic-form-template",
    "formularios y template": "dynamic-form-template",
    "formularios + template": "dynamic-form-template",
    "formularios más template": "dynamic-form-template",
    "formularios mas template": "dynamic-form-template",
    "formulario con templates": "dynamic-form-template",
    "formulario y templates": "dynamic-form-template",
    "formulario + templates": "dynamic-form-template",
    "formulario más templates": "dynamic-form-template",
    "formulario mas templates": "dynamic-form-template",
    "formularios con templates": "dynamic-form-template",
    "formularios y templates": "dynamic-form-template",
    "formularios + templates": "dynamic-form-template",
    "formularios más templates": "dynamic-form-template",
    "formularios mas templates": "dynamic-form-template",
    "template en formulario": "dynamic-form-template",
    "template con formulario": "dynamic-form-template",
    "template de formulario": "dynamic-form-template",
    "template + formulario": "dynamic-form-template",
    "template más formulario": "dynamic-form-template",
    "template mas formulario": "dynamic-form-template",
    "template en formularios": "dynamic-form-template",
    "template con formularios": "dynamic-form-template",
    "template de formularios": "dynamic-form-template",
    "template + formularios": "dynamic-form-template",
    "template más formularios": "dynamic-form-template",
    "template mas formularios": "dynamic-form-template",
    "templates en formulario": "dynamic-form-template",
    "templates con formulario": "dynamic-form-template",
    "templates de formulario": "dynamic-form-template",
    "templates + formulario": "dynamic-form-template",
    "templates más formulario": "dynamic-form-template",
    "templates mas formulario": "dynamic-form-template",
    "templates en formularios": "dynamic-form-template",
    "templates con formularios": "dynamic-form-template",
    "templates de formularios": "dynamic-form-template",
    "templates + formularios": "dynamic-form-template",
    "templates más formularios": "dynamic-form-template",
    "templates mas formularios": "dynamic-form-template",
    # dinámico - dinámicos
    "formulario dinámico": "dynamic-form-general",
    "formulario dinámico con template": "dynamic-form-template",
    "formulario dinámico y template": "dynamic-form-template",
    "formulario dinámico + template": "dynamic-form-template",
    "formulario dinámico más template": "dynamic-form-template",
    "formulario dinámico mas template": "dynamic-form-template",
    "formularios dinámicos con template": "dynamic-form-template",
    "formularios dinámicos y template": "dynamic-form-template",
    "formularios dinámicos + template": "dynamic-form-template",
    "formularios dinámicos más template": "dynamic-form-template",
    "formularios dinámicos mas template": "dynamic-form-template",
    "formulario dinámico con templates": "dynamic-form-template",
    "formulario dinámico y templates": "dynamic-form-template",
    "formulario dinámico + templates": "dynamic-form-template",
    "formulario dinámico más templates": "dynamic-form-template",
    "formulario dinámico mas templates": "dynamic-form-template",
    "formularios dinámicos con templates": "dynamic-form-template",
    "formularios dinámicos y templates": "dynamic-form-template",
    "formularios dinámicos + templates": "dynamic-form-template",
    "formularios dinámicos más templates": "dynamic-form-template",
    "formularios dinámicos mas templates": "dynamic-form-template",
    "template en formulario dinámico": "dynamic-form-template",
    "template con formulario dinámico": "dynamic-form-template",
    "template de formulario dinámico": "dynamic-form-template",
    "template + formulario dinámico": "dynamic-form-template",
    "template más formulario dinámico": "dynamic-form-template",
    "template mas formulario dinámico": "dynamic-form-template",
    "template en formularios dinámicos": "dynamic-form-template",
    "template con formularios dinámicos": "dynamic-form-template",
    "template de formularios dinámicos": "dynamic-form-template",
    "template + formularios dinámicos": "dynamic-form-template",
    "template más formularios dinámicos": "dynamic-form-template",
    "template mas formularios dinámicos": "dynamic-form-template",
    "templates en formulario dinámico": "dynamic-form-template",
    "templates con formulario dinámico": "dynamic-form-template",
    "templates de formulario dinámico": "dynamic-form-template",
    "templates + formulario dinámico": "dynamic-form-template",
    "templates más formulario dinámico": "dynamic-form-template",
    "templates mas formulario dinámico": "dynamic-form-template",
    "templates en formularios dinámicos": "dynamic-form-template",
    "templates con formularios dinámicos": "dynamic-form-template",
    "templates de formularios dinámicos": "dynamic-form-template",
    "templates + formularios dinámicos": "dynamic-form-template",
    "templates más formularios dinámicos": "dynamic-form-template",
    "templates mas formularios dinámicos": "dynamic-form-template",
    # dinamico - dinamicos
    "formulario dinamico": "dynamic-form-general",
    "formulario dinamico con template": "dynamic-form-template",
    "formulario dinamico y template": "dynamic-form-template",
    "formulario dinamico + template": "dynamic-form-template",
    "formulario dinamico más template": "dynamic-form-template",
    "formulario dinamico mas template": "dynamic-form-template",
    "formularios dinamicos con template": "dynamic-form-template",
    "formularios dinamicos y template": "dynamic-form-template",
    "formularios dinamicos + template": "dynamic-form-template",
    "formularios dinamicos más template": "dynamic-form-template",
    "formularios dinamicos mas template": "dynamic-form-template",
    "formulario dinamico con templates": "dynamic-form-template",
    "formulario dinamico y templates": "dynamic-form-template",
    "formulario dinamico + templates": "dynamic-form-template",
    "formulario dinamico más templates": "dynamic-form-template",
    "formulario dinamico mas templates": "dynamic-form-template",
    "formularios dinamicos con templates": "dynamic-form-template",
    "formularios dinamicos y templates": "dynamic-form-template",
    "formularios dinamicos + templates": "dynamic-form-template",
    "formularios dinamicos más templates": "dynamic-form-template",
    "formularios dinamicos mas templates": "dynamic-form-template",
    "template en formulario dinamico": "dynamic-form-template",
    "template con formulario dinamico": "dynamic-form-template",
    "template de formulario dinamico": "dynamic-form-template",
    "template + formulario dinamico": "dynamic-form-template",
    "template más formulario dinamico": "dynamic-form-template",
    "template mas formulario dinamico": "dynamic-form-template",
    "template en formularios dinamicos": "dynamic-form-template",
    "template con formularios dinamicos": "dynamic-form-template",
    "template de formularios dinamicos": "dynamic-form-template",
    "template + formularios dinamicos": "dynamic-form-template",
    "template más formularios dinamicos": "dynamic-form-template",
    "template mas formularios dinamicos": "dynamic-form-template",
    "templates en formulario dinamico": "dynamic-form-template",
    "templates con formulario dinamico": "dynamic-form-template",
    "templates de formulario dinamico": "dynamic-form-template",
    "templates + formulario dinamico": "dynamic-form-template",
    "templates más formulario dinamico": "dynamic-form-template",
    "templates mas formulario dinamico": "dynamic-form-template",
    "templates en formularios dinamicos": "dynamic-form-template",
    "templates con formularios dinamicos": "dynamic-form-template",
    "templates de formularios dinamicos": "dynamic-form-template",
    "templates + formularios dinamicos": "dynamic-form-template",
    "templates más formularios dinamicos": "dynamic-form-template",
    "templates mas formularios dinamicos": "dynamic-form-template",
    # form
    "form": "dynamic-form-general",
    "forms": "dynamic-form-general",
    "form con template": "dynamic-form-template",
    "form con templates": "dynamic-form-template",
    "form y template": "dynamic-form-template",
    "form y templates": "dynamic-form-template",
    "form + template": "dynamic-form-template",
    "form + templates": "dynamic-form-template",
    "form más template": "dynamic-form-template",
    "form más templates": "dynamic-form-template",
    "form mas template": "dynamic-form-template",
    "form mas templates": "dynamic-form-template",
    "forms con template": "dynamic-form-template",
    "forms con templates": "dynamic-form-template",
    "forms y template": "dynamic-form-template",
    "forms y templates": "dynamic-form-template",
    "forms + template": "dynamic-form-template",
    "forms + templates": "dynamic-form-template",
    "forms más template": "dynamic-form-template",
    "forms más templates": "dynamic-form-template",
    "forms mas template": "dynamic-form-template",
    "forms mas templates": "dynamic-form-template",
    "templates de form": "dynamic-form-template",
    "templates de forms": "dynamic-form-template",
    "templates en form": "dynamic-form-template",
    "templates en forms": "dynamic-form-template",    
    "templates con form": "dynamic-form-template",
    "templates con forms": "dynamic-form-template",
    "templates y form": "dynamic-form-template",
    "templates y forms": "dynamic-form-template",
    "templates + form": "dynamic-form-template",
    "templates + forms": "dynamic-form-template",
    "templates mas form": "dynamic-form-template",
    "templates mas forms": "dynamic-form-template",
    "templates más form": "dynamic-form-template",
    "templates más forms": "dynamic-form-template",
    "form template": "dynamic-form-template",
    "form with template": "dynamic-form-template",
    "form and template": "dynamic-form-template",
    "form plus template": "dynamic-form-template",
    "form + template": "dynamic-form-template",
    "form templates": "dynamic-form-template",
    "form with templates": "dynamic-form-template",
    "form and templates": "dynamic-form-template",
    "form more templates": "dynamic-form-template",
    "form + templates": "dynamic-form-template",
    # dynamic form 
    "dynamic form": "dynamic-form-general",
    "dynamic form template": "dynamic-form-template",
    "dynamic form with template": "dynamic-form-template",
    "dynamic form and template": "dynamic-form-template",
    "dynamic form plus template": "dynamic-form-template",
    "dynamic form + template": "dynamic-form-template",
    "dynamic form templates": "dynamic-form-template",
    "dynamic form with templates": "dynamic-form-template",
    "dynamic form and templates": "dynamic-form-template",
    "dynamic form more templates": "dynamic-form-template",
    "dynamic form + templates": "dynamic-form-template",
    # dynamic-form
    "dynamic-form": "dynamic-form-general",
    "dynamic-form template": "dynamic-form-template",
    "dynamic-form with template": "dynamic-form-template",
    "dynamic-form and template": "dynamic-form-template",
    "dynamic-form plus template": "dynamic-form-template",
    "dynamic-form + template": "dynamic-form-template",
    "dynamic-form templates": "dynamic-form-template",
    "dynamic-form with templates": "dynamic-form-template",
    "dynamic-form and templates": "dynamic-form-template",
    "dynamic-form more templates": "dynamic-form-template",
    "dynamic-form + templates": "dynamic-form-template",
}