apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "cumplimientodigital-frontend"
  description: "Repositorio creado para el proyecto cumplimientodigital"
  annotations:
    github.com/project-slug: cumplimiento-digital/"cumplimientodigital-frontend"
    backstage.io/techdocs-ref: dir:.
spec:
  type: component
  lifecycle: experimental
  owner: cumplimiento-digital