apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cumplimientodigital-frontend
  description: Repositorio para el proyecto cumplimiento digital - Frontend Angular 20
  annotations:
    github.com/project-slug: segurosbolivar/cumplimientodigital-frontend
    backstage.io/techdocs-ref: dir:.
spec:
  type: component
  lifecycle: experimental
  owner: cumplimiento-digital