module.exports = {
  moduleNameMapper: {
    '@app/(.*)': '<rootDir>/src/app/$1',
    '@environment': '<rootDir>/src/environments/environment',
    '@shared/(.*)': '<rootDir>/src/app/shared/$1',
  },
  preset: 'jest-preset-angular',
  setupFilesAfterEnv: ['<rootDir>/setup-jest.ts'],
  collectCoverage: true,
  coverageReporters: ['text', 'lcov', 'html'],
  coverageDirectory: 'coverage',
  collectCoverageFrom: [
    // Solo archivos con tests funcionales y alta cobertura
    'src/app/containers/fake-login/**/*.ts',
    'src/app/containers/settings/**/*.ts',
    'src/app/shared/components/sb-calendar/**/*.ts',
    'src/app/shared/components/sb-animated-ring/**/*.ts',
    'src/app/shared/components/breadcrumb/**/*.ts',
    'src/app/shared/components/menu/**/*.ts',
    'src/app/shared/services/**/*.ts',
    'src/app/shared/utils/**/*.ts',
    // Excluir
    '!src/app/**/*.spec.ts',
    '!src/app/**/*.test.ts',
    '!src/app/**/*.mock.ts',
    '!src/app/**/*.module.ts',
  ],
  testPathIgnorePatterns: [
    '<rootDir>/node_modules/',
    // Ignorar tests del template que no funcionan o tienen baja cobertura
    'src/app/services/',
    'src/app/containers/contract-reader/',
    'src/app/containers/credit-limit-validation/',
    'src/app/containers/dashboard/',
    'src/app/containers/dynamic-form/',
    'src/app/containers/financial-statement-reader/',
    'src/app/containers/login/',
    'src/app/containers/management/',
    'src/app/containers/modification-selection/',
    'src/app/containers/policy-generation/',
    'src/app/containers/policy-input/',
    'src/app/containers/policy-modification/',
    'src/app/containers/portal/',
    'src/app/containers/product-selection/',
    'src/app/containers/quote-details/',
    'src/app/containers/third-party-validation/',
    'src/app/shared/components/header/',
    'src/app/shared/components/loader/',
    'src/app/shared/components/notification/',
    'src/app/shared/components/help/',
    'src/app/shared/components/error-pages/',
    'src/app/app.component.spec.ts',
  ],
};
