module.exports = {
  moduleNameMapper: {
    '@app/(.*)': '<rootDir>/src/app/$1',
    '@environment': '<rootDir>/src/environments/environment',
    '@shared/(.*)': '<rootDir>/src/app/shared/$1',
  },
  preset: 'jest-preset-angular',
  setupFilesAfterEnv: ['<rootDir>/setup-jest.ts'],
  collectCoverage: true,
  coverageReporters: ['text', 'lcov', 'html'],
  coverageDirectory: 'coverage',
  // ✅ Solo recolectar cobertura de archivos con tests
  collectCoverageFrom: [
    'src/app/containers/fake-login/**/*.ts',
    'src/app/containers/settings/**/*.ts',
    'src/app/shared/components/sb-calendar/**/*.ts',
    'src/app/shared/utils/**/*.ts',
    '!src/app/**/*.spec.ts',
    '!src/app/**/*.module.ts',
  ],
  // ✅ Solo ejecutar tests que funcionan
  testPathIgnorePatterns: [
    '<rootDir>/node_modules/',
    '<rootDir>/src/app/containers/third-party-validation/',
    '<rootDir>/src/app/containers/financial-statement-reader/',
    '<rootDir>/src/app/containers/policy-generation/',
    '<rootDir>/src/app/containers/policy-input/',
    '<rootDir>/src/app/containers/login/',
    '<rootDir>/src/app/containers/portal/',
    '<rootDir>/src/app/containers/credit-limit-validation/',
    '<rootDir>/src/app/containers/product-selection/',
    '<rootDir>/src/app/containers/modification-selection/',
    '<rootDir>/src/app/containers/quote-details/',
    '<rootDir>/src/app/containers/dynamic-form/',
    '<rootDir>/src/app/services/',
    '<rootDir>/src/app/app.component.spec.ts',
    '<rootDir>/src/app/shared/components/notification/',
    '<rootDir>/src/app/shared/components/loader/',
    '<rootDir>/src/app/shared/components/header/',
  ],
};
