/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}', './projects/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        primaryD400: 'var(--c-lib-tb-primaryD400)',
        primaryD300: 'var(--c-lib-tb-primaryD300)',
        primaryD200: 'var(--c-lib-tb-primaryD200)',
        primaryD100: 'var(--c-lib-tb-primaryD100)',
        primaryBase: 'var(--c-lib-tb-primaryBase)',
        primaryL100: 'var(--c-lib-tb-primaryL100)',
        primaryL200: 'var(--c-lib-tb-primaryL200)',
        primaryL300: 'var(--c-lib-tb-primaryL300)',
        primaryL400: 'var(--c-lib-tb-primaryL400)',

        secondaryD400: 'var(--c-lib-tb-secondaryD400)',
        secondaryD300: 'var(--c-lib-tb-secondaryD300)',
        secondaryD200: 'var(--c-lib-tb-secondaryD200)',
        secondaryD100: 'var(--c-lib-tb-secondaryD100)',
        secondaryBase: 'var(--c-lib-tb-secondaryBase)',
        secondaryL100: 'var(--c-lib-tb-secondaryL100)',
        secondaryL200: 'var(--c-lib-tb-secondaryL200)',
        secondaryL300: 'var(--c-lib-tb-secondaryL300)',
        secondaryL400: 'var(--c-lib-tb-secondaryL400)',

        tertiaryD400: 'var(--c-lib-tb-tertiaryD400)',
        tertiaryD300: 'var(--c-lib-tb-tertiaryD300)',
        tertiaryD200: 'var(--c-lib-tb-tertiaryD200)',
        tertiaryD100: 'var(--c-lib-tb-tertiaryD100)',
        tertiaryBase: 'var(--c-lib-tb-tertiaryBase)',
        tertiaryL100: 'var(--c-lib-tb-tertiaryL100)',
        tertiaryL200: 'var(--c-lib-tb-tertiaryL200)',
        tertiaryL300: 'var(--c-lib-tb-tertiaryL300)',
        tertiaryL400: 'var(--c-lib-tb-tertiaryL400)',

        complementaryD400: 'var(--c-lib-tb-complementaryD400)',
        complementaryD300: 'var(--c-lib-tb-complementaryD300)',
        complementaryD200: 'var(--c-lib-tb-complementaryD200)',
        complementaryD100: 'var(--c-lib-tb-complementaryD100)',
        complementaryBase: 'var(--c-lib-tb-complementaryBase)',
        complementaryL100: 'var(--c-lib-tb-complementaryL100)',
        complementaryL200: 'var(--c-lib-tb-complementaryL200)',
        complementaryL300: 'var(--c-lib-tb-complementaryL300)',
        complementaryL400: 'var(--c-lib-tb-complementaryL400)',

        grayscaleBlack: 'var(--c-lib-tb-grayscaleBlack)',
        grayscaleD400: 'var(--c-lib-tb-grayscaleD400)',
        grayscaleD300: 'var(--c-lib-tb-grayscaleD300)',
        grayscaleD200: 'var(--c-lib-tb-grayscaleD200)',
        grayscaleD100: 'var(--c-lib-tb-grayscaleD100)',
        grayscaleBase: 'var(--c-lib-tb-grayscaleBase)',
        grayscaleL100: 'var(--c-lib-tb-grayscaleL100)',
        grayscaleL200: 'var(--c-lib-tb-grayscaleL200)',
        grayscaleL300: 'var(--c-lib-tb-grayscaleL300)',
        grayscaleL400: 'var(--c-lib-tb-grayscaleL400)',
        grayscaleWhite: 'var(--c-lib-tb-grayscaleWhite)',

        errorD400: 'var(--c-lib-tb-errorD400)',
        errorD300: 'var(--c-lib-tb-errorD300)',
        errorD200: 'var(--c-lib-tb-errorD200)',
        errorD100: 'var(--c-lib-tb-errorD100)',
        errorBase: 'var(--c-lib-tb-errorBase)',
        errorL100: 'var(--c-lib-tb-errorL100)',
        errorL200: 'var(--c-lib-tb-errorL200)',
        errorL300: 'var(--c-lib-tb-errorL300)',
        errorL400: 'var(--c-lib-tb-errorL400)',

        infoD400: 'var(--c-lib-tb-infoD400)',
        infoD300: 'var(--c-lib-tb-infoD300)',
        infoD200: 'var(--c-lib-tb-infoD200)',
        infoD100: 'var(--c-lib-tb-infoD100)',
        infoBase: 'var(--c-lib-tb-infoBase)',
        infoL100: 'var(--c-lib-tb-infoL100)',
        infoL200: 'var(--c-lib-tb-infoL200)',
        infoL300: 'var(--c-lib-tb-infoL300)',
        infoL400: 'var(--c-lib-tb-infoL400)',

        successD400: 'var(--c-lib-tb-successD400)',
        successD300: 'var(--c-lib-tb-successD300)',
        successD200: 'var(--c-lib-tb-successD200)',
        successD100: 'var(--c-lib-tb-successD100)',
        successBase: 'var(--c-lib-tb-successBase)',
        successL100: 'var(--c-lib-tb-successL100)',
        successL200: 'var(--c-lib-tb-successL200)',
        successL300: 'var(--c-lib-tb-successL300)',
        successL400: 'var(--c-lib-tb-successL400)',

        warningD400: 'var(--c-lib-tb-warningD400)',
        warningD300: 'var(--c-lib-tb-warningD300)',
        warningD200: 'var(--c-lib-tb-warningD200)',
        warningD100: 'var(--c-lib-tb-warningD100)',
        warningBase: 'var(--c-lib-tb-warningBase)',
        warningL100: 'var(--c-lib-tb-warningL100)',
        warningL200: 'var(--c-lib-tb-warningL200)',
        warningL300: 'var(--c-lib-tb-warningL300)',
        warningL400: 'var(--c-lib-tb-warningL400)',
      },
    },
  },
  plugins: [],
};
